---
#k3s_version: v1.17.5+k3s1
#k3s_download_url: https://github.com/k3s-io/k3s/releases/download

k3s_version: v1.17.5-k3s1
k3s_download_url: http://rancher-mirror.cnrancher.com/k3s

ansible_user: root
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--node-external-ip {{ master_ip }}"
extra_agent_args: ""